# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urllist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
